### ISSUE TITLE
Cut-off Time

### ISSUE THREAD

**Issue by GrimSeeker** [Gawah/MangoPeel#12]
Version: Steam OS 3.5.17
Deckyloader version: 2.22.1
Mangopeel version:  0.0.5-1

The time is cut off when using the horizontal overlay.
Offsetting the hud doesn't resolve the issue.

![20240229_195003](https://github.com/Gawah/MangoPeel/assets/161794707/4eaa96cc-980a-4fc0-b18d-a8f4ef48c1e8)
![20240229_193332](https://github.com/Gawah/MangoPeel/assets/161794707/9094b52e-df19-4182-a5e7-e0992ce6316e)

**Comment by wrathek** [comment]
Seconding this issue. It isn't cutoff for me, however it just sits on top of the FPS column as if it doesn't exist. Only started happenign recently (probably a decky update issue or something).

**Comment by Gawah** [comment]
It can be confirmed that this is an issue with mangohud, which occurs when horizontal layout and time are enabled at the same time. This plugin is only used to modify the parameter configuration of mangohud.
![Uploading d327f024-f71f-4251-8cc7-b93c8e64f918.png…]()

**Comment by GrimSeeker** [comment]
Issue appears to be resolved in the Steam OS 3.6.19 update
