### ISSUE TITLE
Make OffsetX/Y negative for bottom/right positions

### ISSUE THREAD

**Issue by OddMorning** [Gawah/MangoPeel#9]
OffsetX and OffestY work great with default position (`top-left`)
![PXL_20231215_142800846](https://github.com/Gawah/MangoPeel/assets/12204657/97cab572-1d2c-4fd2-b1fd-10af11c8a472)

But these options shift overlay beyond the screen when custom position enabled.

For example, `bottom-left`:
![PXL_20231215_142812475](https://github.com/Gawah/MangoPeel/assets/12204657/d07e2687-0dab-4209-a4da-78761361beb4)

Or `top-right`:
![PXL_20231215_142830704](https://github.com/Gawah/MangoPeel/assets/12204657/7a4227d4-cc69-4893-8f3b-a30343ec918b)

---

I think the best solution would be to invert the offset values. For example, `OffsetY = 20` in UI would internally become `OffsetY = -20` when `Position = bottom-left`. If it is possible of course

**Comment by Gawah** [comment]
I've adjusted the range of the offset, and now it is [-2160, 2160]. You can adjust the values according to your needs. However, I believe that even [0, 2160] is sufficient to meet the requirements. Theoretically, you can move the HUD to any location on the screen using offsetx + offsety, without the need to configure the position.

**Comment by Gawah** [comment]
This range change will take effect in the next plugin update.
